on:
  pull_request:
    types: [opened, edited, reopened]
    paths: 
      - '**.js'

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test eslint-changeset action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - run: |
          git fetch --no-tags --depth=1 origin main
          git checkout main 
          git checkout -
      - name: Eslint Changeset Step
        uses: ./
        id: eslint-changeset
        with:
          main-branch: 'main'
          file-extension: 'js'