on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test eslint-changeset action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git fetch --no-tags --depth=1 origin main
          git checkout main 
          echo '+++++++++++++++++++++++++++++++++++++++++++'
          echo ${{ github.event.pull_request.head.sha }}
          echo '+++++++++++++++++++++++++++++++++++++++++++'
          git checkout ${{ github.event.pull_request.head.sha }}
      - name: Eslint Changeset Step
        uses: ./ # Uses an action in the root directory
        id: eslint-changeset
        with:
          main-branch: 'main'
          file-extension: 'js'